name: Test
on:
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
      - Makefile
      - 'docs/**/*'
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - Makefile
      - 'docs/**/*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4

      - name: Set up Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.16
        id: go

      - name: Get Dependencies
        run: go mod download

      - name: Build
        run: go build -v .
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.15'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4

      - name: Get dependencies
        run: go mod download

      - name: TF Acceptance Tests
        timeout-minutes: 10
        env:
          TF_ACC: '1'
        run: go test -v -cover ./solana/...
